In [1]:
import cube_x3d as c3
import numpy as np

In [46]:
import importlib
importlib.reload(c3)

<module 'cube_x3d' from 'c:\\Users\\ixaka\\Documents\\Visualization\\cube_x3d\\cube_x3d.py'>

In [2]:
%cd C:\\Users\\ixaka\\Documents\\Visualization

C:\Users\ixaka\Documents\Visualization


In [3]:
#HCG31
lims = np.array([[60, 500-61],
                 [100, 500-91],
                 [90, 265-81]])

In [4]:
isolevels = np.array([1.5, 3.5, 6.5, 11])

In [ ]:
c = '0 0 1'
# HCG31 all from LVM et al. (2005)
gals = {'HCG31a':{'v':4090,'col':c},
       'HCG31b':{'v':4122,'col':c},
       'HCG31c':{'v':3984,'col':c},
        'HCG31g':{'v':4005,'col':c},
        'HCG31q':{'v':4090,'col':c}
       }

In [5]:
gals = ['HCG31a', 'HCG31b', 'HCG31c', 'HCG31g', 'HCG31q']

In [6]:
#(['DSS2 Blue'], '2500,2500')
un = np.array([-1,'arcsec', 'arcsec', 'km/s']) #units that we want to have

In [47]:
file = c3.main('HCG31.fits', isolevels=None, units=un,
                gals=None, image2d=None, lims=None)

[[ 7.52996987e+01  7.55082192e+01]
 [-4.36082634e+00 -4.15290956e+00]
 [ 3.25498130e+06  4.71062352e+06]]
Automatic isolevels = [0.18760830163955688, 0.37521660327911377, 0.6253610054651896, 1.2507220109303792]


In [48]:
file.choose_buttons(picking=False, galaxies=False, gallab=False, image2d=False, move2d=False)

In [49]:
file.make('cube_x3d/examples/HCG31_te')

[[-374.25020656    0.          374.25020656]
 [-374.25020192    0.          374.25020192]
 [-727.82110786    0.          727.82110786]]


IndexError: invalid index to scalar variable.