In [1]:
import cube_x3d_old as c3
import numpy as np

In [46]:
import importlib
importlib.reload(c3)

<module 'cube_x3d' from 'c:\\Users\\ixaka\\Documents\\Visualization\\cube_x3d\\cube_x3d.py'>

In [3]:
#HCG31
name = "HCG31"
lims = np.array([[60, 500-61],
                 [100, 500-91],
                 [90, 265-81]])
c = '0 0 1'
# HCG31 all from LVM et al. (2005)
gals = {'HCG31a':{'v':4090,'col':c},
       'HCG31b':{'v':4122,'col':c},
       'HCG31c':{'v':3984,'col':c},
        'HCG31g':{'v':4005,'col':c},
        'HCG31q':{'v':4090,'col':c}
       }
isolevels = [1.5, 3.5, 6.5, 11]

In [ ]:
#HCG16
# Limits to crop the cube, no HI there. Subtract 1 to wanted number, e.g. nz-1.
name = "HCG16"
lims = np.array([[80, 315-16],
                [50, 280-11],
                [0, 133-1]])
c = '0 0 1'
# HCG16 from Hickson 1992
gals = {'HCG16a':{'v':4152,'col':c},
       'HCG16b':{'v':3977,'col':c},
       'HCG16c':{'v':3851,'col':c},
        'HCG16d':{'v':3847,'col':c},
        'NGC848':{'v':4001, 'col':c}
       }
isolevels = [1.5, 4.5, 8.5, 13]

In [23]:
#HCG91
# Limits to crop the cube, no HI there. Subtract 1 to wanted number, e.g. nz-1.
name = "HCG91"
lims = np.array([[100, 256-101],
                 [100, 256-81],
                 [10, 58-11]])
c = '0 0 1'
# HCG91 from Hickson 1992
gals = {'HCG91a':{'v':6832,'col':c},
       'HCG91b':{'v':7196,'col':c},
       'HCG91c':{'v':7319,'col':c},
        'HCG91d':{'v':7195,'col':c}
       }
isolevels = [1.5, 2.5, 3.5, 6]

In [6]:
#(['DSS2 Blue'], '2500,2500')
un = np.array([-1,'arcsec', 'arcsec', 'km/s']) #units that we want to have

In [47]:
file = c3.main('HCG31.fits', isolevels=None, units=un,
                gals=None, image2d=None, lims=None)

Cube deltas = [-1.5         1.5        -5.51379627] in arcsec,arcsec and km/s
Data in mJy / beam
Automatic isolevels = [1.876082992553711, 3.752165985107422, 6.253609975179036, 12.507219950358072]
Done.


In [48]:
file.choose_buttons(picking=False, galaxies=False, gallab=False, image2d=False, move2d=False)

In [49]:
file.make('cube_x3d/examples/HCG31_te')

[[-374.25020656    0.          374.25020656]
 [-374.25020192    0.          374.25020192]
 [-727.82110786    0.          727.82110786]]


IndexError: invalid index to scalar variable.